########################
# COMPARE M
########################

# --- Preperatory steps
# 1) replace " " by "_" in the output file generated by CompareM aai_wf
# 2) Refer to the correct path in CompareM = read.table("<path to file>",header=TRUE) 

########################

#install if needed
install.packages(c("igraph","gplots","RColorBrewer","FactoMineR","ggplot2","Hmisc","ade4"),dependencies=TRUE)

#load packages
library(igraph)
library(gplots)
library(RColorBrewer)
library(FactoMineR)
library(ggplot2)
library(Hmisc)
library(ade4)

#load the CompareM data (Get rid of the spaces in headers in text-editor!)
CompareM =read.table("~/DATA/MarinobacterGenomics/miscl/CompareM/aai_summary.tsv",header=TRUE)
#CompareM =read.table("~/DATA/MarinobacterGenomics/miscl/CompareM/AAI_oceanospirilalles.tsv",header=TRUE)

#show graphically
ggplot(data=CompareM,aes(x= Mean_AAI,y=Orthologous_fraction_.OF.))+geom_point()+geom_smooth(col="darkgreen",method="lm",se = TRUE)+theme_classic()
ggplot(data=CompareM,aes(x= Mean_AAI,y= orthologous_genes))+geom_point()+geom_point()+geom_smooth(col="darkgreen",method="lm",se = TRUE)+theme_classic()

# correlations
cor(CompareM$Mean_AAI, CompareM$orthologous_genes)
cor(CompareM$Mean_AAI, CompareM$Orthologous_fraction_.OF.)

# statistics of linear regression
summary(lm(CompareM$orthologous_genes ~ CompareM$Mean_AAI))
summary(lm(CompareM$Orthologous_fraction_.OF. ~ CompareM$Mean_AAI))

#transform the data in a matrix format
dat = CompareM[,c("Genome_A","Genome_B","Mean_AAI")]
g <- graph.data.frame(dat, directed=FALSE)
AAI = get.adjacency(g, attr="Mean_AAI", sparse=FALSE)

#genomes compared to themselves have 100 as a value
AAI[AAI<1] <- 100

#heatmap
heatmap.2(AAI,trace="none",col = colorRampPalette(c("red", "black", "yellow","darkgreen"))(40))

#PCA
CompM.pca <- PCA(AAI)
plot(CompM.pca,cex=0.5)

#same, but for the Orhologous fraction
dat = CompareM[,c("Genome_A","Genome_B","Orthologous_fraction_.OF.")]
g <- graph.data.frame(dat, directed=FALSE)
OF = get.adjacency(g, attr="Orthologous_fraction_.OF.", sparse=FALSE)
OF[OF <1] <- 100
heatmap.2(OF,trace="none",col = colorRampPalette(c("red", "black", "yellow","darkgreen"))(40))

CompM.pca <- PCA(OF)
plot(CompM.pca,cex=0.5)

#same, but for the Orhologous fraction
dat = CompareM[,c("Genome_A","Genome_B","orthologous_genes")]
g <- graph.data.frame(dat, directed=FALSE)
Og = get.adjacency(g, attr="orthologous_genes", sparse=FALSE)
Og[Og<1] <- NA
heatmap.2(Og,trace="none",na.color="white",col = colorRampPalette(c("red", "black", "yellow","darkgreen"))(40))

CompM.pca <- PCA(Og)
plot(CompM.pca,cex=0.5)


######### - statistics - ##########

# Mantel test 
#H0 - matrices are different, Ha - matrices correlate
mantel.rtest(as.dist(AAI), as.dist(OF), nrepet = 999)
